-- ============================================
-- SCHEMA NORMALIZATION MIGRATION
-- ============================================

-- 1. Create EXTENSION for text search
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- 2. Modify Profiles
ALTER TABLE profiles 
ADD COLUMN IF NOT EXISTS account_status text DEFAULT 'active' CHECK (account_status IN ('active','disabled')),
ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now();

-- Ensure roles are correctly constrained
ALTER TABLE profiles DROP CONSTRAINT IF EXISTS profiles_role_check;
ALTER TABLE profiles ADD CONSTRAINT profiles_role_check CHECK (role IN ('admin','member','subscriber'));

-- 3. Membership Plans
CREATE TABLE IF NOT EXISTS membership_plans (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    code text UNIQUE NOT NULL,
    name text NOT NULL,
    member_stats_access boolean DEFAULT false,
    price_amount numeric,
    billing_interval text,
    is_active boolean DEFAULT true,
    created_at timestamptz DEFAULT now()
);

-- 4. Memberships
CREATE TABLE IF NOT EXISTS memberships (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id uuid REFERENCES profiles(id) ON DELETE CASCADE,
    plan_id uuid REFERENCES membership_plans(id),
    status text CHECK (status IN ('pending','active','inactive','expired','cancelled','past_due')),
    starts_at timestamptz,
    ends_at timestamptz,
    source text,
    provider text,
    provider_customer_id text,
    provider_subscription_id text,
    metadata jsonb,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- 5. Taxonomy (Category Groups & Options)
CREATE TABLE IF NOT EXISTS category_groups (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug text UNIQUE NOT NULL,
    name text NOT NULL,
    sort_order int DEFAULT 0,
    is_active boolean DEFAULT true
);

CREATE TABLE IF NOT EXISTS category_options (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id bigint REFERENCES category_groups(id) ON DELETE CASCADE,
    slug text NOT NULL,
    name text NOT NULL,
    search_aliases text[],
    sort_order int DEFAULT 0,
    is_active boolean DEFAULT true,
    UNIQUE(group_id, slug)
);

-- 6. Modify Listings
-- Safely handle renames and additions
DO $$
BEGIN
    -- Rename user_id to owner_user_id if owner_user_id doesn't exist
    IF EXISTS(SELECT 1 FROM information_schema.columns WHERE table_name='listings' AND column_name='user_id') AND
       NOT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_name='listings' AND column_name='owner_user_id') THEN
        ALTER TABLE listings RENAME COLUMN user_id TO owner_user_id;
    END IF;
    
    -- Rename phone to contact_phone if it exists
    IF EXISTS(SELECT 1 FROM information_schema.columns WHERE table_name='listings' AND column_name='phone') AND
       NOT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_name='listings' AND column_name='contact_phone') THEN
        ALTER TABLE listings RENAME COLUMN phone TO contact_phone;
    END IF;
END $$;

ALTER TABLE listings 
ADD COLUMN IF NOT EXISTS slug text UNIQUE,
ADD COLUMN IF NOT EXISTS category_group_id bigint REFERENCES category_groups(id),
ADD COLUMN IF NOT EXISTS category_option_id bigint REFERENCES category_options(id),
ADD COLUMN IF NOT EXISTS parish text,
ADD COLUMN IF NOT EXISTS location_display text,
ADD COLUMN IF NOT EXISTS requested_tier text,
ADD COLUMN IF NOT EXISTS admin_note text,
ADD COLUMN IF NOT EXISTS rejection_reason text,
ADD COLUMN IF NOT EXISTS featured_until timestamptz,
ADD COLUMN IF NOT EXISTS published_at timestamptz,
ADD COLUMN IF NOT EXISTS approved_at timestamptz,
ADD COLUMN IF NOT EXISTS approved_by uuid REFERENCES profiles(id),
ADD COLUMN IF NOT EXISTS expires_at timestamptz,
ADD COLUMN IF NOT EXISTS search_document tsvector;

-- Update the check constraint for status
ALTER TABLE listings DROP CONSTRAINT IF EXISTS listings_status_check;
ALTER TABLE listings ADD CONSTRAINT listings_status_check CHECK (status IN ('draft','pending','changes_requested','approved','rejected','expired','archived'));

-- 7. Listing Media
CREATE TABLE IF NOT EXISTS listing_media (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    listing_id uuid REFERENCES listings(id) ON DELETE CASCADE,
    storage_path text UNIQUE NOT NULL,
    mime_type text,
    file_size_bytes bigint,
    alt_text text,
    sort_order int DEFAULT 0,
    is_primary boolean DEFAULT false,
    created_by uuid REFERENCES profiles(id),
    created_at timestamptz DEFAULT now(),
    deleted_at timestamptz
);

-- 8. Listing Status History
CREATE TABLE IF NOT EXISTS listing_status_history (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id uuid REFERENCES listings(id) ON DELETE CASCADE,
    old_status text,
    new_status text,
    changed_by uuid REFERENCES profiles(id),
    reason text,
    snapshot jsonb,
    created_at timestamptz DEFAULT now()
);

-- 9. Admin Audit Log
CREATE TABLE IF NOT EXISTS admin_audit_log (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id uuid REFERENCES profiles(id),
    entity_type text,
    entity_id text,
    action text,
    before_state jsonb,
    after_state jsonb,
    created_at timestamptz DEFAULT now()
);

-- 10. Site Presence Sessions
CREATE TABLE IF NOT EXISTS site_presence_sessions (
    session_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id uuid REFERENCES profiles(id),
    session_kind text CHECK (session_kind IN ('guest','member')),
    started_at timestamptz DEFAULT now(),
    last_seen_at timestamptz DEFAULT now(),
    user_agent_hash text,
    ip_hash text
);

-- 11. Indexes
CREATE INDEX IF NOT EXISTS idx_memberships_user_status ON memberships(user_id, status);
CREATE INDEX IF NOT EXISTS idx_category_groups_sort ON category_groups(sort_order);
CREATE INDEX IF NOT EXISTS idx_category_options_sort ON category_options(group_id, sort_order);
CREATE INDEX IF NOT EXISTS idx_listings_owner_created ON listings(owner_user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_listings_status_created ON listings(status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_listing_media_listing_sort ON listing_media(listing_id, sort_order);
CREATE INDEX IF NOT EXISTS idx_listing_status_history_listing ON listing_status_history(listing_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_admin_audit_log_actor ON admin_audit_log(actor_user_id, created_at DESC);

-- Trigram indexes for text search
CREATE INDEX IF NOT EXISTS listings_business_name_trgm_idx ON listings USING gin (business_name gin_trgm_ops);
CREATE INDEX IF NOT EXISTS listings_location_display_trgm_idx ON listings USING gin (location_display gin_trgm_ops);
CREATE INDEX IF NOT EXISTS listings_search_document_idx ON listings USING gin (search_document);

-- Update search_document trigger instead of generated column so it can be managed with coalesce
CREATE OR REPLACE FUNCTION update_search_document() RETURNS TRIGGER AS $$
BEGIN
    NEW.search_document := to_tsvector('english',
        coalesce(NEW.business_name, '') || ' ' ||
        coalesce(NEW.description, '') || ' ' ||
        coalesce(NEW.parish, '') || ' ' ||
        coalesce(NEW.location_display, '')
    );
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_update_search_document ON listings;
CREATE TRIGGER trg_update_search_document
    BEFORE INSERT OR UPDATE ON listings
    FOR EACH ROW EXECUTE PROCEDURE update_search_document();

-- ============================================
-- PRIVATE HELPERS & RLS ENFORCEMENT
-- ============================================

CREATE SCHEMA IF NOT EXISTS private;

CREATE OR REPLACE FUNCTION private.is_admin(p_uid uuid DEFAULT auth.uid())
RETURNS boolean AS $$
BEGIN
    RETURN EXISTS (
        SELECT 1 FROM public.profiles 
        WHERE id = p_uid AND role = 'admin'
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = '';

CREATE OR REPLACE FUNCTION private.has_active_membership(p_uid uuid DEFAULT auth.uid())
RETURNS boolean AS $$
BEGIN
    RETURN EXISTS (
        SELECT 1 FROM public.memberships 
        WHERE user_id = p_uid AND status = 'active'
        AND (ends_at IS NULL OR ends_at > now())
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = '';

-- ============================================
-- RLS POLICIES LOCKDOWN
-- ============================================

ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE membership_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE memberships ENABLE ROW LEVEL SECURITY;
ALTER TABLE category_groups ENABLE ROW LEVEL SECURITY;
ALTER TABLE category_options ENABLE ROW LEVEL SECURITY;
ALTER TABLE listings ENABLE ROW LEVEL SECURITY;
ALTER TABLE listing_media ENABLE ROW LEVEL SECURITY;
ALTER TABLE listing_status_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE admin_audit_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE site_presence_sessions ENABLE ROW LEVEL SECURITY;

-- Profiles: Own row, Admin full
DROP POLICY IF EXISTS "Profiles viewable by owner or admin" ON profiles;
CREATE POLICY "Profiles viewable by owner or admin" ON profiles FOR SELECT
USING (id = (SELECT auth.uid()) OR private.is_admin((SELECT auth.uid())));

DROP POLICY IF EXISTS "Profiles updatable by owner or admin" ON profiles;
CREATE POLICY "Profiles updatable by owner or admin" ON profiles FOR UPDATE
USING (id = (SELECT auth.uid()) OR private.is_admin((SELECT auth.uid())));

-- Plans: Public read, Admin full
DROP POLICY IF EXISTS "Active plans viewable by public" ON membership_plans;
CREATE POLICY "Active plans viewable by public" ON membership_plans FOR SELECT
USING (is_active = true OR private.is_admin((SELECT auth.uid())));

-- Memberships: Owner read, Admin full
DROP POLICY IF EXISTS "Memberships viewable by owner or admin" ON memberships;
CREATE POLICY "Memberships viewable by owner or admin" ON memberships FOR SELECT
USING (user_id = (SELECT auth.uid()) OR private.is_admin((SELECT auth.uid())));

-- Category Groups & Options: Public read
DROP POLICY IF EXISTS "Category groups viewable by public" ON category_groups;
CREATE POLICY "Category groups viewable by public" ON category_groups FOR SELECT
USING (is_active = true OR private.is_admin((SELECT auth.uid())));

DROP POLICY IF EXISTS "Category options viewable by public" ON category_options;
CREATE POLICY "Category options viewable by public" ON category_options FOR SELECT
USING (is_active = true OR private.is_admin((SELECT auth.uid())));

-- Listings
DROP POLICY IF EXISTS "Approved listings are public" ON listings;
CREATE POLICY "Approved listings are public" ON listings FOR SELECT
USING (
    (status = 'approved' AND (expires_at IS NULL OR expires_at > now()) AND (published_at IS NULL OR published_at <= now()))
    OR owner_user_id = (SELECT auth.uid())
    OR private.is_admin((SELECT auth.uid()))
);

DROP POLICY IF EXISTS "Users insert own listings" ON listings;
CREATE POLICY "Users insert own listings" ON listings FOR INSERT
WITH CHECK (owner_user_id = (SELECT auth.uid()));

DROP POLICY IF EXISTS "Users update editable listings" ON listings;
CREATE POLICY "Users update editable listings" ON listings FOR UPDATE
USING (
    (owner_user_id = (SELECT auth.uid()) AND status IN ('draft','pending','changes_requested'))
    OR private.is_admin((SELECT auth.uid()))
);

-- Listing Media
DROP POLICY IF EXISTS "Media viewable by owner or admin" ON listing_media;
CREATE POLICY "Media viewable by owner or admin" ON listing_media FOR SELECT
USING (
    created_by = (SELECT auth.uid())
    OR private.is_admin((SELECT auth.uid()))
    -- Public media reading will be via signed URLs or bucket policy directly, not table read.
);

DROP POLICY IF EXISTS "Users insert own media" ON listing_media;
CREATE POLICY "Users insert own media" ON listing_media FOR INSERT
WITH CHECK (created_by = (SELECT auth.uid()));

-- Status History
DROP POLICY IF EXISTS "History viewable by owner or admin" ON listing_status_history;
CREATE POLICY "History viewable by owner or admin" ON listing_status_history FOR SELECT
USING (
    EXISTS (SELECT 1 FROM listings l WHERE l.id = listing_id AND l.owner_user_id = (SELECT auth.uid()))
    OR private.is_admin((SELECT auth.uid()))
);

-- Audit Log (Admin only)
DROP POLICY IF EXISTS "Audit log admin only" ON admin_audit_log;
CREATE POLICY "Audit log admin only" ON admin_audit_log FOR ALL
USING (private.is_admin((SELECT auth.uid())));

-- Presence
DROP POLICY IF EXISTS "Presence viewable by owner or admin" ON site_presence_sessions;
CREATE POLICY "Presence viewable by owner or admin" ON site_presence_sessions FOR SELECT
USING (user_id = (SELECT auth.uid()) OR private.is_admin((SELECT auth.uid())));

-- Drop old functions moving to Edge Functions
DROP FUNCTION IF EXISTS get_member_stats();
DROP FUNCTION IF EXISTS get_admin_stats();
DROP FUNCTION IF EXISTS admin_update_listing(uuid, text, boolean);
DROP FUNCTION IF EXISTS admin_get_listings(text, integer, integer);
DROP FUNCTION IF EXISTS admin_set_user_role(uuid, text);
